env:
  es6: true
  node: true

extends: 
  - 'eslint:recommended'

parserOptions:
  ecmaVersion: "2017"
  sourceType: module

rules:
  indent:
    - error
    - 4
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - allowTemplateLiterals: true
  semi:
    - error
    - always
  no-console: 0
  eol-last:
    - error
    - always
  async-await/space-after-async: 2
  async-await/space-after-await: 2

plugins:
  - async-await
